// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3q6NZf9_nBAwe_rTHgSYPW_zRjO8Vkmw',
    appId: '1:760531940922:web:5e743452d096d280fba703',
    messagingSenderId: '760531940922',
    projectId: 'chronos-b4ad2',
    authDomain: 'chronos-b4ad2.firebaseapp.com',
    storageBucket: 'chronos-b4ad2.firebasestorage.app',
    measurementId: 'G-KJS1CSD0GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfbOEhPGZdq-Y_N785WCbdGj-IBjW1rRw',
    appId: '1:760531940922:android:898e5a119b77d96cfba703',
    messagingSenderId: '760531940922',
    projectId: 'chronos-b4ad2',
    storageBucket: 'chronos-b4ad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqyuJZoUfOW_o92-mxf3U9qRuS7jIap0',
    appId: '1:760531940922:ios:50b2f0a1ec952538fba703',
    messagingSenderId: '760531940922',
    projectId: 'chronos-b4ad2',
    storageBucket: 'chronos-b4ad2.firebasestorage.app',
    iosBundleId: 'com.example.chronos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeqyuJZoUfOW_o92-mxf3U9qRuS7jIap0',
    appId: '1:760531940922:ios:50b2f0a1ec952538fba703',
    messagingSenderId: '760531940922',
    projectId: 'chronos-b4ad2',
    storageBucket: 'chronos-b4ad2.firebasestorage.app',
    iosBundleId: 'com.example.chronos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3q6NZf9_nBAwe_rTHgSYPW_zRjO8Vkmw',
    appId: '1:760531940922:web:33f32de5927b1564fba703',
    messagingSenderId: '760531940922',
    projectId: 'chronos-b4ad2',
    authDomain: 'chronos-b4ad2.firebaseapp.com',
    storageBucket: 'chronos-b4ad2.firebasestorage.app',
    measurementId: 'G-GFJ0LCENQG',
  );
}
